services:
  client:
    image: vimal1026/frontend:${TAG}
    container_name: frontend
    ports:
      - "5174:5174"
    depends_on:
      - server

  server:
    image: vimal1026/backend:${TAG}
    container_name: backend
    ports:
      - "8001:8001"