name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      # Build backend
      - run: npm ci
        working-directory: ./server
      - run: npm run build
        working-directory: ./server

      # Build frontend
      - run: npm ci
        working-directory: ./client
      - run: npm run build
        working-directory: ./client

      # Docker login
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build backend image
      - uses: docker/build-push-action@v5
        with:
          context: ./server
          push: true
          tags: vimal1026/backend:${{ github.sha }}

      # Build frontend image
      - uses: docker/build-push-action@v5
        with:
          context: ./client
          push: true
          tags: vimal1026/frontend:${{ github.sha }}

  deploy-prod:
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - name: Create PROD SSH key
        run: |
          echo "${{ secrets.PROD_EC2_KEY }}" > prod_key.pem
          chmod 600 prod_key.pem

      - name: Deploy to PROD EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i prod_key.pem ${{ secrets.PROD_EC2_USER }}@${{ secrets.PROD_EC2_HOST }} << EOF
            cd ${{ secrets.PROD_APP_DIR }}/docker-compose
            export TAG=${{ github.sha }}
            docker compose pull
            docker compose up -d
          EOF
